# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.
default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  db_host: <%= ENV['DATABASE_HOST'] %>
  db_username: <%= ENV['DATABASE_USERNAME'] %>
  db_password: <%= ENV['DATABASE_PASSWORD'] %>
  db_name: <%= ENV['DATABASE_NAME'] %>


development:
  <<: *default
  secret_key_base: a523919abb9ada2fc2a94403978cdee3a6306573b6252f11fbc21eceaba145a121e44cd1b9090e34cfe42dbbdf6bb6c8dc5aad64ecad2af30b6d251c2e0865f2

test:
  <<: *default
  secret_key_base: a74421be3d7ca1c2ecf7ab9c3cd5f4c0fcc0ba218b539ac11abb29686465790d84ea7a4567eee9e16b2ac629556e0fcc774aa1ba9df91c706d02db7213ca6b74

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  <<: *default
