global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'redirect'

rule_files:
  # - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'postgresql'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'postgres-exporter:9187'

  - job_name: 'admin'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'admin:3000'

  - job_name: 'redirector'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'redirector:8080'
